#!/bin/bash

# fail on any error
set -o errexit

# debug
#set -x

DATABASE_HOST=$1
DATABASE_PORT=$2
NEW_DATABASE_NAME=$3
NEW_DATABASE_USER=$4
NEW_DATABASE_PASSWORD=$5

MYSQLCMD="mysql --no-auto-rehash --host=$DATABASE_HOST --port=$DATABASE_PORT --user=$DATABASE_ROOT_USER --password=$DATABASE_ROOT_PASSWORD"
#MYSQLCMD="$MYSQLCMD --ssl_ca=rds-ssl-ca-cert.pem --ssl-verify-server-cert"

MYSQLCMD=cat

echo "CREATE DATABASE $NEW_DATABASE_NAME DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;" | $MYSQLCMD
echo "CREATE USER '$NEW_DATABASE_USER'@'%' IDENTIFIED BY '$NEW_DATABASE_PASSWORD';" | $MYSQLCMD
echo "GRANT ALL PRIVILEGES ON $NEW_DATABASE_NAME.* to '$NEW_DATABASE_USER'@'%' IDENTIFIED BY '$NEW_DATABASE_PASSWORD';" | $MYSQLCMD
echo "FLUSH PRIVILEGES;" | $MYSQLCMD
